from flask_wtf import FlaskForm
from wtforms import StringField, DateField, TextAreaField, SubmitField, PasswordField, SelectMultipleField, SelectField, BooleanField, FloatField, IntegerField
from wtforms.validators import DataRequired, Length, Optional, NumberRange
from app.models import STRUCTURES

class LoginForm(FlaskForm):
    username=StringField("Nom d'utilisateur",validators=[DataRequired(),Length(max=150)]); password=PasswordField("Mot de passe",validators=[DataRequired()]); submit=SubmitField("Se connecter")
class DownloadExcelForm(FlaskForm): submit=SubmitField("Télécharger en Excel")
class ProspectionForm(FlaskForm):
    date=DateField("Date",validators=[DataRequired()]); prospect_id=SelectField("Prospect",choices=[],coerce=int,validators=[Optional()]); nom_client=StringField("Nom du prospect",validators=[DataRequired(),Length(max=150)]); specialite=StringField("Service / spécialité",validators=[DataRequired(),Length(max=150)]); structure=SelectField("Type de structure",choices=[],validators=[DataRequired(),Length(max=150)]); establishment=SelectField("Établissement",choices=[],validators=[DataRequired(),Length(max=200)]); telephone=StringField("Téléphone",validators=[DataRequired(),Length(max=30)]); profils_prospect=TextAreaField("Profils prospect"); produits_presentes=SelectMultipleField("Produits présentés",choices=[],validators=[Optional()]); produits_prescrits=SelectMultipleField("Produits prescrits",choices=[],validators=[Optional()]); submit=SubmitField("Enregistrer")
class PlanningForm(FlaskForm):
    date=DateField("Date de début de la semaine",validators=[DataRequired()]); lundi=SelectMultipleField("Lundi",choices=STRUCTURES); mardi=SelectMultipleField("Mardi",choices=STRUCTURES); mercredi=SelectMultipleField("Mercredi",choices=STRUCTURES); jeudi=SelectMultipleField("Jeudi",choices=STRUCTURES); vendredi=SelectMultipleField("Vendredi",choices=STRUCTURES); samedi=SelectMultipleField("Samedi",choices=STRUCTURES); dimanche=SelectMultipleField("Dimanche",choices=STRUCTURES); submit=SubmitField("Valider le planning")
class SupplierSalesForm(FlaskForm): sale_date=DateField("Date de saisie",validators=[DataRequired()]); submit=SubmitField("Enregistrer les ventes")
class CSRFOnlyForm(FlaskForm): pass
class UserForm(FlaskForm):
    username=StringField("Nom d'utilisateur",validators=[DataRequired(),Length(max=150)]); role=SelectField("Rôle",choices=[("commercial","Commercial"),("admin","Administrateur")],validators=[DataRequired()]); project=SelectField("Division",choices=[("nasderm","NASDERM"),("nasmedic","NASMEDIC")],validators=[DataRequired()]); zone=StringField("Zone",validators=[Optional(),Length(max=100)]); password=PasswordField("Mot de passe",validators=[Optional(),Length(min=8,message="8 caractères minimum.")]); is_active_account=BooleanField("Compte actif",default=True); submit=SubmitField("Enregistrer")
class ProductForm(FlaskForm):
    name=StringField("Nom du produit",validators=[DataRequired(),Length(max=200)]); reference=StringField("Référence / code produit",validators=[Optional(),Length(max=100)]); default_price=FloatField("Prix HT par défaut (€)",validators=[DataRequired(),NumberRange(min=0,message="Le prix ne peut pas être négatif.")]); is_active=BooleanField("Référence active",default=True); submit=SubmitField("Enregistrer")
class SaleEditForm(FlaskForm):
    date=DateField("Date de vente",validators=[DataRequired()]); quantity=IntegerField("Quantité vendue",validators=[DataRequired(),NumberRange(min=1,message="La quantité doit être supérieure à 0.")]); price=FloatField("Prix HT unitaire (€)",validators=[DataRequired(),NumberRange(min=0,message="Le prix ne peut pas être négatif.")]); submit=SubmitField("Enregistrer")
class ObjectiveForm(FlaskForm):
    annual_target=FloatField("Objectif annuel (€)",validators=[Optional(),NumberRange(min=0)]); jan=FloatField("Janvier (€)",validators=[Optional(),NumberRange(min=0)]); feb=FloatField("Février (€)",validators=[Optional(),NumberRange(min=0)]); mar=FloatField("Mars (€)",validators=[Optional(),NumberRange(min=0)]); apr=FloatField("Avril (€)",validators=[Optional(),NumberRange(min=0)]); may=FloatField("Mai (€)",validators=[Optional(),NumberRange(min=0)]); jun=FloatField("Juin (€)",validators=[Optional(),NumberRange(min=0)]); jul=FloatField("Juillet (€)",validators=[Optional(),NumberRange(min=0)]); aug=FloatField("Août (€)",validators=[Optional(),NumberRange(min=0)]); sep=FloatField("Septembre (€)",validators=[Optional(),NumberRange(min=0)]); oct=FloatField("Octobre (€)",validators=[Optional(),NumberRange(min=0)]); nov=FloatField("Novembre (€)",validators=[Optional(),NumberRange(min=0)]); dec=FloatField("Décembre (€)",validators=[Optional(),NumberRange(min=0)]); submit=SubmitField("Enregistrer les objectifs")
class EvaluationForm(FlaskForm):
    score_ca=FloatField("Atteinte de l'objectif de CA",validators=[Optional(),NumberRange(min=0,max=20)]); score_gamme_asthe=FloatField("Gamme — Asthe 1000",validators=[Optional(),NumberRange(min=0,max=2)]); score_gamme_myocalm=FloatField("Gamme — Myocalm",validators=[Optional(),NumberRange(min=0,max=2)]); score_gamme_bumbum=FloatField("Gamme — Bum Bum",validators=[Optional(),NumberRange(min=0,max=1)]); score_gamme_flatupklexin=FloatField("Gamme — Flatupklexin",validators=[Optional(),NumberRange(min=0,max=2)]); score_gamme_somniplex=FloatField("Gamme — Somniplex",validators=[Optional(),NumberRange(min=0,max=1)]); score_gamme_ostheophytum=FloatField("Gamme — Ostheophytum",validators=[Optional(),NumberRange(min=0,max=1)]); score_gamme_specialkid=FloatField("Gamme — Spécial Kid",validators=[Optional(),NumberRange(min=0,max=1)]); score_reporting=FloatField("Qualité du reporting & nombre de visites",validators=[Optional(),NumberRange(min=0,max=10)]); score_plan_visite=FloatField("Respect du plan de visite & ciblage",validators=[Optional(),NumberRange(min=0,max=10)]); score_argumentaire=FloatField("Qualité de l'argumentaire scientifique",validators=[Optional(),NumberRange(min=0,max=10)]); score_prescriptions=FloatField("Capacité à générer des prescriptions",validators=[Optional(),NumberRange(min=0,max=10)]); score_organisation=FloatField("Organisation, discipline & gestion matériel",validators=[Optional(),NumberRange(min=0,max=5)]); score_ponctualite=FloatField("Ponctualité, assiduité et présence",validators=[Optional(),NumberRange(min=0,max=10)]); score_consignes=FloatField("Respect des consignes & directives",validators=[Optional(),NumberRange(min=0,max=10)]); score_esprit_equipe=FloatField("Esprit d'équipe, proactivité & attitude",validators=[Optional(),NumberRange(min=0,max=5)]); points_forts=TextAreaField("Points forts",validators=[Optional()]); axes_amelioration=TextAreaField("Axes d'amélioration",validators=[Optional()]); objectifs_quantitatifs=TextAreaField("Objectifs quantitatifs (mois suivant)",validators=[Optional()]); objectifs_qualitatifs=TextAreaField("Objectifs qualitatifs (mois suivant)",validators=[Optional()]); submit=SubmitField("Enregistrer l'évaluation")