"""add sales_objective table

Revision ID: 103f34c10e01
Revises: 1e8d8abf327e
Create Date: 2026-08-18 09:19:48.553264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103f34c10e01'
down_revision = '1e8d8abf327e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_objective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('division', 'year', 'month', name='uq_objective_division_year_month')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_objective')
    # ### end Alembic commands ###
