"""add reference and is_active to product references

Revision ID: 1e8d8abf327e
Revises: 86532002e87a
Create Date: 2026-08-08 10:05:09.764226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8d8abf327e'
down_revision = '86532002e87a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eric_favre_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('gilbert_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('nova_pharma_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('trois_chene_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trois_chene_product', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('reference')

    with op.batch_alter_table('nova_pharma_product', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('reference')

    with op.batch_alter_table('gilbert_product', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('reference')

    with op.batch_alter_table('eric_favre_product', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
