"""initial schema

Revision ID: 4dd8d1c9e1f3
Revises: 
Create Date: 2026-08-07 09:22:48.661545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd8d1c9e1f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eric_favre_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_price', sa.Float(), nullable=False),
    sa.Column('stock_duopharm', sa.Integer(), nullable=False),
    sa.Column('stock_ubipharm', sa.Integer(), nullable=False),
    sa.Column('stock_laborex', sa.Integer(), nullable=False),
    sa.Column('stock_sodipharm', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gilbert_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_price', sa.Float(), nullable=False),
    sa.Column('stock_duopharm', sa.Integer(), nullable=False),
    sa.Column('stock_ubipharm', sa.Integer(), nullable=False),
    sa.Column('stock_laborex', sa.Integer(), nullable=False),
    sa.Column('stock_sodipharm', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nova_pharma_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_price', sa.Float(), nullable=False),
    sa.Column('stock_duopharm', sa.Integer(), nullable=False),
    sa.Column('stock_ubipharm', sa.Integer(), nullable=False),
    sa.Column('stock_laborex', sa.Integer(), nullable=False),
    sa.Column('stock_sodipharm', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trois_chene_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_price', sa.Float(), nullable=False),
    sa.Column('stock_duopharm', sa.Integer(), nullable=False),
    sa.Column('stock_ubipharm', sa.Integer(), nullable=False),
    sa.Column('stock_laborex', sa.Integer(), nullable=False),
    sa.Column('stock_sodipharm', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('project', sa.String(length=50), nullable=False),
    sa.Column('is_active_account', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('eric_favre_sale',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('commercial_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['commercial_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['eric_favre_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eric_favre_sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eric_favre_sale_date'), ['date'], unique=False)

    op.create_table('gilbert_sale',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('commercial_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['commercial_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['gilbert_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gilbert_sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gilbert_sale_date'), ['date'], unique=False)

    op.create_table('nova_pharma_sale',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('commercial_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['commercial_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['nova_pharma_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nova_pharma_sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nova_pharma_sale_date'), ['date'], unique=False)

    op.create_table('planning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commercial_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lundi_matin', sa.String(length=255), nullable=True),
    sa.Column('lundi_soir', sa.String(length=255), nullable=True),
    sa.Column('mardi_matin', sa.String(length=255), nullable=True),
    sa.Column('mardi_soir', sa.String(length=255), nullable=True),
    sa.Column('mercredi_matin', sa.String(length=255), nullable=True),
    sa.Column('mercredi_soir', sa.String(length=255), nullable=True),
    sa.Column('jeudi_matin', sa.String(length=255), nullable=True),
    sa.Column('jeudi_soir', sa.String(length=255), nullable=True),
    sa.Column('vendredi_matin', sa.String(length=255), nullable=True),
    sa.Column('vendredi_soir', sa.String(length=255), nullable=True),
    sa.Column('samedi_matin', sa.String(length=255), nullable=True),
    sa.Column('samedi_soir', sa.String(length=255), nullable=True),
    sa.Column('dimanche_matin', sa.String(length=255), nullable=True),
    sa.Column('dimanche_soir', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['commercial_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planning', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planning_commercial_id'), ['commercial_id'], unique=False)

    op.create_table('prospection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commercial_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nom_client', sa.String(length=150), nullable=False),
    sa.Column('specialite', sa.String(length=150), nullable=False),
    sa.Column('structure', sa.String(length=150), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=False),
    sa.Column('profils_prospect', sa.Text(), nullable=True),
    sa.Column('produits_presentes', sa.Text(), nullable=True),
    sa.Column('produits_prescrits', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['commercial_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prospection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prospection_commercial_id'), ['commercial_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospection_date'), ['date'], unique=False)

    op.create_table('trois_chene_sale',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('commercial_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['commercial_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['trois_chene_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trois_chene_sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trois_chene_sale_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trois_chene_sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trois_chene_sale_date'))

    op.drop_table('trois_chene_sale')
    with op.batch_alter_table('prospection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prospection_date'))
        batch_op.drop_index(batch_op.f('ix_prospection_commercial_id'))

    op.drop_table('prospection')
    with op.batch_alter_table('planning', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planning_commercial_id'))

    op.drop_table('planning')
    with op.batch_alter_table('nova_pharma_sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nova_pharma_sale_date'))

    op.drop_table('nova_pharma_sale')
    with op.batch_alter_table('gilbert_sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gilbert_sale_date'))

    op.drop_table('gilbert_sale')
    with op.batch_alter_table('eric_favre_sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eric_favre_sale_date'))

    op.drop_table('eric_favre_sale')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('trois_chene_product')
    op.drop_table('nova_pharma_product')
    op.drop_table('gilbert_product')
    op.drop_table('eric_favre_product')
    # ### end Alembic commands ###
